import random  
import stories 

def select_random_story():
    # Pulls data from a stored story
    if not stories.all_stories:
        print("No stories found! Please add stories to stories.py")
        return None # Return None if no stories are available
    
    selected_story_data = random.choice(stories.all_stories)
    return selected_story_data

def get_user_inputs_for_story(placeholders, story_title):
    # User inputs
    print(f"\nLet's play: {story_title.upper()}")
    print("*" * 3 + f"This story needs {len(placeholders)} words." + "*" * 3)
    print("\nPlease enter the following words for the story:")

    user_inputs = {}
    for placeholder in placeholders:
        prompt_text = placeholder.replace("_", " ").capitalize()
        while True:
            user_word = input(f"Enter a {prompt_text}: ")
            if user_word.strip():
                break
            else:
                print("Oops! You need to enter a word.")
        user_inputs[placeholder] = user_word
    return user_inputs

def build_and_display_story(template, inputs, title):
    # Assembles and prints the story
    print("\n" + "*" * 15 + f" {title.upper()} - YOUR COMPLETED MAD LIB! " + "*" * 15)
    final_story = template.format(**inputs)
    print(final_story)
    return final_story

def handle_save_story(story_text, story_title):
    # Saving the story as a text file
    while True:
        save_choice = input("Would you like to save this story to a file? (Y/N): ").upper()
        if save_choice in ['Y', 'N']:
            break
        else:
            print("Invalid input. Please enter 'Y' or 'N'.")

    if save_choice == 'Y':
        safe_title = "".join(c if c.isalnum() or c == '_' else "" for c in story_title.lower().replace(" ", "_"))
        filename_suggestion = f"{safe_title[:20]}_madlibs.txt" if safe_title else "madlibs_story.txt"
        
        while True:
            filename = input(f"Enter a filename (e.g., {filename_suggestion}): ")
            if not filename.strip():
                filename = filename_suggestion
            if not filename.endswith(".txt"):
                filename += ".txt"
            
            try:
                with open(filename, 'w') as f:
                    f.write(f"Title: {story_title}\n")
                    f.write("-" * len(f"Title: {story_title}") + "\n")
                    f.write(story_text)
                    f.write("\n\n---\nGenerated by Beginner MadLibs!")
                print(f"Story successfully saved to {filename}")
                break
            except IOError:
                print(f"Error: Could not save '{filename}'. Try a different name/check permissions.")
            except Exception as e:
                print(f"An unexpected error occurred: {e}. Please try another filename.")