import random
import stories

while True:

    # Setting up the game
    print("Welcome to Mad Libs!")
    selected_story_data = random.choice(stories.all_stories)
    story_template = selected_story_data['template']
    required_placeholders = selected_story_data['placeholders']    
    
    # User word entry
    print(f"\nThis story needs {len(required_placeholders)} words.")
    print("\nPlease enter the following words for the story:")
    user_inputs = {}
    for placeholder in required_placeholders:
        user_word = input(f"Enter a {placeholder}:")
        user_inputs[placeholder] = user_word

    # Printing the story itself
    print("\n--- Your Mad Libs Story ---")
    final_story = story_template.format(**user_inputs)
    print(final_story)

    # Ask the user if they want to save the story
    while True:
        save_choice = input("Would you like to save this story as a text file? (Y/N)").upper()
        if save_choice in ["Y", "N"]:
            break
        else:
            print("Please enter 'Y' or 'N' only. I am a scrub and this is the best I can do.")

    # Saving the file
    if save_choice == "Y":
        while True:
            filename_suggestion = "savels_madlibs_story.txt"
            filename = input(f"Please name your file (e.g. {filename_suggestion})")
            if not filename.endswith(".txt"):
                filename += ".txt"
            try:
                with open(filename, 'w') as f:
                    f.write("Your Awesome Mad Libs Story:\n")
                    f.write("----------------------------\n")
                    f.write(final_story)
                    f.write("\n----------------------------\nGenerated by Savel's Beginner MadLibs!")
                print(f"Story sucessfully saved to {filename}")
                break
            except Exception as e:
                print(f"An unexpected error occurred: {e}. Please try a different filename.")

    # Repeat the program to play again
    play_again = input("Would you like to play again? (Y/N)")
    if play_again.upper() != "Y":
        print("Thanks again for playing! Goodbye.")
        break
    else:
        print("Okay, let's play again!")
